#!/usr/bin/env python3

import sys
import http.server
import socketserver

PORT = 8000
DIRECTORY = "mock_pdc"

class CORSRequestHandler(http.server.SimpleHTTPRequestHandler):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, directory=DIRECTORY, **kwargs)

	def end_headers(self):
		self.send_header("Access-Control-Allow-Origin", "*")
		return super().end_headers()

if __name__ == "__main__":
	with socketserver.TCPServer(("0.0.0.0", PORT), CORSRequestHandler) as httpd:
		print(f"Serving at 0.0.0.0:{PORT}")
		try:
			httpd.serve_forever()
		except KeyboardInterrupt:
			print("\nKeyboard interrupt received, exiting.")
			sys.exit(0)
